import type { College } from './types';

/**
 * Additional Government Colleges Database
 * 
 * Instructions for adding more colleges in the future:
 * 1. Copy the template below
 * 2. Fill in real, verified data
 * 3. Required fields: all except optional ones marked with ?
 * 4. Get coordinates from Google Maps
 * 5. Verify contact info from official website
 */

export const additionalColleges: College[] = [
    // ==================== ANDHRA PRADESH & TELANGANA ====================
    {
        id: 'spmvv-tirupati',
        name: 'Sri Padmavati Mahila Visvavidyalayam, Tirupati',
        district: 'Tirupati',
        state: 'Andhra Pradesh',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'B.Sc. Biotechnology'],
        eligibility: '10+2. Women-only university.',
        imageUrl: 'https://picsum.photos/seed/spmvv/600/400',
        about: 'Indias first state-funded womens university, dedicated to empowering women through quality education in arts, science, and commerce.',
        level: 'after_12th',
        fee: 'Rs. 8,000 - Rs. 15,000 per year',
        scholarships: 'State government scholarships for SC/ST/OBC/Minority/EWS.',
        latitude: 13.6333,
        longitude: 79.4167,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=13.6333,79.4167',
        contactInfo: {
            phone: '+91-877-228-7007',
            email: 'info@spmvv.ac.in',
            website: 'https://www.spmvv.ac.in',
            address: 'Tirupati, Andhra Pradesh 517502'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 10,000 - Rs. 18,000 per year',
        mediumOfInstruction: ['English', 'Telugu'],
        establishedYear: 1983,
        affiliation: 'State University',
        placementRate: 55
    },

    {
        id: 'jntuh-ceh',
        name: 'JNTUH College of Engineering, Hyderabad',
        district: 'Hyderabad',
        state: 'Telangana',
        type: 'Government',
        courses: ['B.Tech CSE', 'B.Tech ECE', 'B.Tech Mechanical', 'B.Tech Civil'],
        eligibility: '10+2 with PCM. Admission through TS EAMCET.',
        imageUrl: 'https://picsum.photos/seed/jntuhceh/600/400',
        about: 'Constituent college of JNTU Hyderabad, known for excellent technical education and strong industry connections.',
        level: 'after_12th',
        fee: 'Rs. 35,000 - Rs. 40,000 per year',
        scholarships: 'TS Fee Reimbursement Scheme available for eligible students.',
        latitude: 17.5081,
        longitude: 78.3947,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=17.5081,78.3947',
        contactInfo: {
            phone: '+91-40-2315-6103',
            email: 'principal@jntuhceh.ac.in',
            website: 'https://jntuhceh.ac.in',
            address: 'Kukatpally, Hyderabad 500085'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 15,000 - Rs. 25,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1965,
        affiliation: 'JNTUH',
        placementRate: 85,
        averagePackage: '7.5 LPA'
    },

    {
        id: 'kakatiya-univ',
        name: 'Kakatiya University, Warangal',
        district: 'Warangal',
        state: 'Telangana',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'BCA'],
        eligibility: '10+2. Admission through DOST counseling.',
        imageUrl: 'https://picsum.photos/seed/kakatiya/600/400',
        about: 'Premier state university in Telangana, known for science and arts programs with excellent research facilities.',
        level: 'after_12th',
        fee: 'Rs. 5,000 - Rs. 20,000 per year',
        scholarships: 'Telangana state scholarships available for various categories.',
        latitude: 17.9784,
        longitude: 79.5941,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=17.9784,79.5941',
        contactInfo: {
            phone: '+91-870-245-9000',
            email: 'registrar@kakatiya.ac.in',
            website: 'https://www.kakatiya.ac.in',
            address: 'Vidyaranyapuri, Warangal 506009'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 8,000 - Rs. 15,000 per year',
        mediumOfInstruction: ['English', 'Telugu'],
        establishedYear: 1976,
        affiliation: 'State University',
        placementRate: 60
    },

    // ==================== TAMIL NADU ====================
    {
        id: 'madras-univ',
        name: 'University of Madras, Chennai',
        district: 'Chennai',
        state: 'Tamil Nadu',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'B.Sc. Visual Communication'],
        eligibility: '10+2. Admission based on 12th marks.',
        imageUrl: 'https://picsum.photos/seed/madrasuniv/600/400',
        about: 'One of Indias oldest universities, established in 1857. Offers comprehensive undergraduate and postgraduate programs.',
        level: 'after_12th',
        fee: 'Rs. 3,000 - Rs. 12,000 per year',
        scholarships: 'TN government scholarships for various categories.',
        latitude: 13.0569,
        longitude: 80.2497,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=13.0569,80.2497',
        contactInfo: {
            phone: '+91-44-2539-5224',
            email: 'registrar@unom.ac.in',
            website: 'https://www.unom.ac.in',
            address: 'Chepauk, Chennai 600005'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 6,000 - Rs. 12,000 per year',
        mediumOfInstruction: ['English', 'Tamil'],
        establishedYear: 1857,
        affiliation: 'State University',
        nirfRank: 28,
        placementRate: 70,
        averagePackage: '6 LPA'
    },

    {
        id: 'govt-arts-cbe',
        name: 'Government Arts College, Coimbatore',
        district: 'Coimbatore',
        state: 'Tamil Nadu',
        type: 'Government',
        courses: ['B.A. English', 'B.A. Tamil', 'B.Sc. Maths', 'B.Sc. Physics', 'B.Com'],
        eligibility: '10+2. Admission based on marks.',
        imageUrl: 'https://picsum.photos/seed/cbearts/600/400',
        about: 'Premier government arts college in Coimbatore with excellent track record since 1875.',
        level: 'after_12th',
        fee: 'Rs. 1,500 - Rs. 5,000 per year',
        scholarships: 'State scholarships and fee concessions available.',
        latitude: 11.0168,
        longitude: 76.9558,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=11.0168,76.9558',
        contactInfo: {
            phone: '+91-422-239-1268',
            email: 'gaccbe@tn.gov.in',
            website: 'http://www.gacbe.ac.in',
            address: 'Avinashi Road, Coimbatore 641018'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 5,000 - Rs. 10,000 per year',
        mediumOfInstruction: ['English', 'Tamil'],
        establishedYear: 1875,
        affiliation: 'Bharathiar University'
    },

    // ==================== KARNATAKA ====================
    {
        id: 'bangalore-univ',
        name: 'Bangalore University, Bengaluru',
        district: 'Bengaluru',
        state: 'Karnataka',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'BCA'],
        eligibility: '10+2. Admission through university counseling.',
        imageUrl: 'https://picsum.photos/seed/bloreuniv/600/400',
        about: 'Major state university in Karnataka with multiple constituent colleges across the state.',
        level: 'after_12th',
        fee: 'Rs. 5,000 - Rs. 15,000 per year',
        scholarships: 'Karnataka state scholarships for SC/ST/OBC.',
        latitude: 12.9716,
        longitude: 77.5946,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=12.9716,77.5946',
        contactInfo: {
            phone: '+91-80-2296-1315',
            email: 'registrar@bangaloreuniversity.ac.in',
            website: 'https://www.bangaloreuniversity.ac.in',
            address: 'Jnana Bharathi Campus, Bengaluru 560056'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 8,000 - Rs. 18,000 per year',
        mediumOfInstruction: ['English', 'Kannada'],
        establishedYear: 1964,
        affiliation: 'State University',
        placementRate: 65
    },

    {
        id: 'gec-hassan',
        name: 'Government Engineering College, Hassan',
        district: 'Hassan',
        state: 'Karnataka',
        type: 'Government',
        courses: ['B.E. Civil', 'B.E. Mechanical', 'B.E. ECE', 'B.E. CSE'],
        eligibility: '10+2 with PCM. Admission through KCET.',
        imageUrl: 'https://picsum.photos/seed/hassanengg/600/400',
        about: 'Government engineering college in Hassan district with strong technical programs.',
        level: 'after_12th',
        fee: 'Rs. 20,000 - Rs. 30,000 per year',
        scholarships: 'State fee reimbursement for eligible students.',
        latitude: 13.0050,
        longitude: 76.0965,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=13.0050,76.0965',
        contactInfo: {
            phone: '+91-8172-268-003',
            email: 'principal@gechassan.ac.in',
            website: 'http://www.gechassan.ac.in',
            address: 'B.M. Road, Hassan 573201'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 12,000 - Rs. 20,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1963,
        affiliation: 'VTU',
        placementRate: 75,
        averagePackage: '4.5 LPA'
    },

    // ==================== MAHARASHTRA ====================
    {
        id: 'mumbai-univ',
        name: 'University of Mumbai, Mumbai',
        district: 'Mumbai',
        state: 'Maharashtra',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BMS', 'B.Sc. IT'],
        eligibility: '10+2. Admission based on merit.',
        imageUrl: 'https://picsum.photos/seed/mumbaiuniv/600/400',
        about: 'Premier state university in Mumbai, one of the largest in the world with over 700 affiliated colleges.',
        level: 'after_12th',
        fee: 'Rs. 5,000 - Rs. 20,000 per year',
        scholarships: 'Maharashtra state scholarships available for various categories.',
        latitude: 18.9750,
        longitude: 72.8258,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=18.9750,72.8258',
        contactInfo: {
            phone: '+91-22-2652-7654',
            email: 'info@mu.ac.in',
            website: 'https://www.mu.ac.in',
            address: 'Kalina Campus, Santacruz East, Mumbai 400098'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 15,000 - Rs. 30,000 per year',
        mediumOfInstruction: ['English', 'Marathi'],
        establishedYear: 1857,
        affiliation: 'State University',
        nirfRank: 41,
        placementRate: 72
    },

    {
        id: 'pune-univ',
        name: 'Savitribai Phule Pune University, Pune',
        district: 'Pune',
        state: 'Maharashtra',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'B.Sc. Computer Science'],
        eligibility: '10+2. Admission through university counseling.',
        imageUrl: 'https://picsum.photos/seed/puneuniv/600/400',
        about: 'Major state university in Pune, formerly University of Pune, with strong research focus.',
        level: 'after_12th',
        fee: 'Rs. 3,000 - Rs. 15,000 per year',
        scholarships: 'State and central government scholarships available.',
        latitude: 18.5089,
        longitude: 73.8174,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=18.5089,73.8174',
        contactInfo: {
            phone: '+91-20-2560-1001',
            email: 'registrar@unipune.ac.in',
            website: 'http://www.unipune.ac.in',
            address: 'Ganeshkhind, Pune 411007'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 8,000 - Rs. 20,000 per year',
        mediumOfInstruction: ['English', 'Marathi'],
        establishedYear: 1949,
        affiliation: 'State University',
        nirfRank: 39,
        placementRate: 68
    },

    // ==================== WEST BENGAL ====================
    {
        id: 'calcutta-univ',
        name: 'University of Calcutta, Kolkata',
        district: 'Kolkata',
        state: 'West Bengal',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA'],
        eligibility: '10+2. Admission based on merit.',
        imageUrl: 'https://picsum.photos/seed/calcuttauniv/600/400',
        about: 'One of the oldest universities in India, established in 1857. Rich heritage in arts and sciences.',
        level: 'after_12th',
        fee: 'Rs. 2,000 - Rs. 10,000 per year',
        scholarships: 'State and central scholarships available.',
        latitude: 22.5726,
        longitude: 88.3639,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=22.5726,88.3639',
        contactInfo: {
            phone: '+91-33-2241-0071',
            email: 'registrar@caluniv.ac.in',
            website: 'https://www.caluniv.ac.in',
            address: 'College Street, Kolkata 700073'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 5,000 - Rs. 12,000 per year',
        mediumOfInstruction: ['English', 'Bengali'],
        establishedYear: 1857,
        affiliation: 'State University',
        nirfRank: 25,
        placementRate: 70
    },

    // ==================== UTTAR PRADESH ====================
    {
        id: 'lucknow-univ',
        name: 'University of Lucknow, Lucknow',
        district: 'Lucknow',
        state: 'Uttar Pradesh',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'BCA'],
        eligibility: '10+2. Admission based on entrance test.',
        imageUrl: 'https://picsum.photos/seed/lucknowuniv/600/400',
        about: 'Premier state university in Uttar Pradesh with comprehensive academic programs.',
        level: 'after_12th',
        fee: 'Rs. 5,000 - Rs. 15,000 per year',
        scholarships: 'UP government scholarships available.',
        latitude: 26.8467,
        longitude: 80.9462,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=26.8467,80.9462',
        contactInfo: {
            phone: '+91-522-274-0003',
            email: 'info@lkouniv.ac.in',
            website: 'https://www.lkouniv.ac.in',
            address: 'University Road, Lucknow 226007'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 8,000 - Rs. 18,000 per year',
        mediumOfInstruction: ['English', 'Hindi'],
        establishedYear: 1920,
        affiliation: 'State University',
        placementRate: 62
    },

    {
        id: 'allahabad-univ',
        name: 'University of Allahabad, Prayagraj',
        district: 'Prayagraj',
        state: 'Uttar Pradesh',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'LLB', 'BCA'],
        eligibility: '10+2. Admission through entrance test.',
        imageUrl: 'https://picsum.photos/seed/allahabaduniv/600/400',
        about: 'Central university, one of the oldest in India with strong academic heritage.',
        level: 'after_12th',
        fee: 'Rs. 3,000 - Rs. 12,000 per year',
        scholarships: 'Central and state scholarships available.',
        latitude: 25.4358,
        longitude: 81.8463,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=25.4358,81.8463',
        contactInfo: {
            phone: '+91-532-246-0993',
            email: 'registrar@allduniv.ac.in',
            website: 'https://www.allduniv.ac.in',
            address: 'Senate House Campus, Prayagraj 211002'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 6,000 - Rs. 15,000 per year',
        mediumOfInstruction: ['English', 'Hindi'],
        establishedYear: 1887,
        affiliation: 'Central University',
        nirfRank: 43,
        placementRate: 65
    },

    // ==================== RAJASTHAN ====================
    {
        id: 'rajasthan-univ',
        name: 'University of Rajasthan, Jaipur',
        district: 'Jaipur',
        state: 'Rajasthan',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'BCA'],
        eligibility: '10+2. Admission based on merit.',
        imageUrl: 'https://picsum.photos/seed/rajasthanuniv/600/400',
        about: 'Oldest university in Rajasthan state, established right after independence.',
        level: 'after_12th',
        fee: 'Rs. 5,000 - Rs. 15,000 per year',
        scholarships: 'Rajasthan state scholarships available.',
        latitude: 26.9124,
        longitude: 75.7873,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=26.9124,75.7873',
        contactInfo: {
            phone: '+91-141-270-6106',
            email: 'info@uniraj.ac.in',
            website: 'https://www.uniraj.ac.in',
            address: 'JLN Marg, Jaipur 302004'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 8,000 - Rs. 16,000 per year',
        mediumOfInstruction: ['English', 'Hindi'],
        establishedYear: 1947,
        affiliation: 'State University',
        placementRate: 60
    },

    // ==================== GUJARAT ====================
    {
        id: 'gujarat-univ',
        name: 'Gujarat University, Ahmedabad',
        district: 'Ahmedabad',
        state: 'Gujarat',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'BCA'],
        eligibility: '10+2. Admission based on merit.',
        imageUrl: 'https://picsum.photos/seed/gujaratuniv/600/400',
        about: 'Major state university in Gujarat, one of the oldest and largest in the state.',
        level: 'after_12th',
        fee: 'Rs. 4,000 - Rs. 12,000 per year',
        scholarships: 'Gujarat state scholarships for SC/ST/SEBC/EWS.',
        latitude: 23.0225,
        longitude: 72.5714,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=23.0225,72.5714',
        contactInfo: {
            phone: '+91-79-2630-6856',
            email: 'registrar@gujaratuniversity.ac.in',
            website: 'https://www.gujaratuniversity.ac.in',
            address: 'Navrangpura, Ahmedabad 380009'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 8,000 - Rs. 15,000 per year',
        mediumOfInstruction: ['English', 'Gujarati', 'Hindi'],
        establishedYear: 1949,
        affiliation: 'State University',
        placementRate: 64
    },

    {
        id: 'ms-univ-baroda',
        name: 'Maharaja Sayajirao University of Baroda, Vadodara',
        district: 'Vadodara',
        state: 'Gujarat',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'B.Sc. IT'],
        eligibility: '10+2. Admission based on merit.',
        imageUrl: 'https://picsum.photos/seed/msuniv/600/400',
        about: 'Premier university in Gujarat with strong academic reputation and research facilities.',
        level: 'after_12th',
        fee: 'Rs. 5,000 - Rs. 18,000 per year',
        scholarships: 'State and central government scholarships available.',
        latitude: 22.3072,
        longitude: 73.1812,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=22.3072,73.1812',
        contactInfo: {
            phone: '+91-265-279-5201',
            email: 'registrar@msubaroda.ac.in',
            website: 'https://www.msubaroda.ac.in',
            address: 'Pratapgunj, Vadodara 390002'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 10,000 - Rs. 20,000 per year',
        mediumOfInstruction: ['English', 'Gujarati'],
        establishedYear: 1949,
        affiliation: 'State University',
        nirfRank: 31,
        placementRate: 70,
        averagePackage: '5.5 LPA'
    },

    // ==================== BIHAR ====================
    {
        id: 'patna-univ',
        name: 'Patna University, Patna',
        district: 'Patna',
        state: 'Bihar',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA'],
        eligibility: '10+2. Admission based on merit.',
        imageUrl: 'https://picsum.photos/seed/patnauniv/600/400',
        about: 'One of the oldest universities in India, established in 1917. Major center for education in Bihar.',
        level: 'after_12th',
        fee: 'Rs. 3,000 - Rs. 10,000 per year',
        scholarships: 'Bihar state scholarships and central schemes available.',
        latitude: 25.6093,
        longitude: 85.1376,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=25.6093,85.1376',
        contactInfo: {
            phone: '+91-612-2232-568',
            email: 'registrar@patnauniversity.ac.in',
            website: 'http://www.patnauniversity.ac.in',
            address: 'Ashok Rajpath, Patna 800005'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 6,000 - Rs. 12,000 per year',
        mediumOfInstruction: ['English', 'Hindi'],
        establishedYear: 1917,
        affiliation: 'State University',
        placementRate: 55
    },

    {
        id: 'nit-patna',
        name: 'National Institute of Technology, Patna',
        district: 'Patna',
        state: 'Bihar',
        type: 'Government',
        courses: ['B.Tech CSE', 'B.Tech ECE', 'B.Tech Mechanical', 'B.Tech Civil', 'B.Arch'],
        eligibility: '10+2 with PCM. Admission through JEE Main.',
        imageUrl: 'https://picsum.photos/seed/nitpatna/600/400',
        about: 'NIT Patna is one of the premier technical institutes in Eastern India with excellent placement records.',
        level: 'after_12th',
        fee: 'Rs. 1,25,000 per year',
        scholarships: 'Fee remission for SC/ST/PwD. Merit scholarships available.',
        latitude: 25.6207,
        longitude: 85.1720,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=25.6207,85.1720',
        contactInfo: {
            phone: '+91-612-237-1715',
            email: 'registrar@nitp.ac.in',
            website: 'https://www.nitp.ac.in',
            address: 'Ashok Rajpath, Patna 800005'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 15,000 - Rs. 25,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1886,
        affiliation: 'NIT (Institute of National Importance)',
        nirfRank: 64,
        placementRate: 88,
        averagePackage: '10.5 LPA'
    },

    // ==================== ODISHA ====================
    {
        id: 'utkal-univ',
        name: 'Utkal University, Bhubaneswar',
        district: 'Bhubaneswar',
        state: 'Odisha',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'BCA'],
        eligibility: '10+2. Admission based on Plus Two marks.',
        imageUrl: 'https://picsum.photos/seed/utkaluniv/600/400',
        about: 'Oldest university in Odisha, established in 1943. Major center for higher education in the state.',
        level: 'after_12th',
        fee: 'Rs. 3,500 - Rs. 12,000 per year',
        scholarships: 'Odisha state scholarships and central schemes available.',
        latitude: 20.2961,
        longitude: 85.8245,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=20.2961,85.8245',
        contactInfo: {
            phone: '+91-674-256-7832',
            email: 'registrar@utkaluniversity.ac.in',
            website: 'http://www.utkaluniversity.ac.in',
            address: 'Vani Vihar, Bhubaneswar 751004'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 6,000 - Rs. 14,000 per year',
        mediumOfInstruction: ['English', 'Odia'],
        establishedYear: 1943,
        affiliation: 'State University',
        placementRate: 58
    },

    {
        id: 'nit-rourkela',
        name: 'National Institute of Technology, Rourkela',
        district: 'Rourkela',
        state: 'Odisha',
        type: 'Government',
        courses: ['B.Tech CSE', 'B.Tech Metallurgical', 'B.Tech Chemical', 'B.Tech Mining', 'B.Arch'],
        eligibility: '10+2 with PCM. Admission through JEE Main.',
        imageUrl: 'https://picsum.photos/seed/nitrourkela/600/400',
        about: 'One of the top NITs in India, known for metallurgy and engineering programs.',
        level: 'after_12th',
        fee: 'Rs. 1,25,000 per year',
        scholarships: 'Fee waivers for SC/ST and income-based scholarships.',
        latitude: 22.2502,
        longitude: 84.9016,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=22.2502,84.9016',
        contactInfo: {
            phone: '+91-661-246-2020',
            email: 'registrar@nitrkl.ac.in',
            website: 'https://www.nitrkl.ac.in',
            address: 'Rourkela, Odisha 769008'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 18,000 - Rs. 28,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1961,
        affiliation: 'NIT (Institute of National Importance)',
        nirfRank: 16,
        placementRate: 90,
        averagePackage: '12 LPA'
    },

    // ==================== KERALA ====================
    {
        id: 'kerala-univ',
        name: 'University of Kerala, Thiruvananthapuram',
        district: 'Thiruvananthapuram',
        state: 'Kerala',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'B.Sc. Data Science'],
        eligibility: '10+2. Admission through university allotment.',
        imageUrl: 'https://picsum.photos/seed/keralauniv/600/400',
        about: 'First university in Kerala, established in 1937. Premier institution for higher education in the state.',
        level: 'after_12th',
        fee: 'Rs. 4,000 - Rs. 15,000 per year',
        scholarships: 'Kerala state scholarships for SC/ST/OBC/Minority students.',
        latitude: 8.4801,
        longitude: 76.9491,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=8.4801,76.9491',
        contactInfo: {
            phone: '+91-471-230-7316',
            email: 'universitykl@keralauniversity.ac.in',
            website: 'https://www.keralauniversity.ac.in',
            address: 'Palayam, Thiruvananthapuram 695034'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 8,000 - Rs. 18,000 per year',
        mediumOfInstruction: ['English', 'Malayalam'],
        establishedYear: 1937,
        affiliation: 'State University',
        placementRate: 65
    },

    {
        id: 'calicut-univ',
        name: 'University of Calicut, Calicut',
        district: 'Malappuram',
        state: 'Kerala',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'B.Voc'],
        eligibility: '10+2. Admission through CAP (Centralised Allotment Process).',
        imageUrl: 'https://picsum.photos/seed/calicutuniv/600/400',
        about: 'Largest university in Kerala in terms of student enrollment, established in 1968.',
        level: 'after_12th',
        fee: 'Rs. 3,500 - Rs. 14,000 per year',
        scholarships: 'State and central scholarships for eligible categories.',
        latitude: 11.1246,
        longitude: 75.8364,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=11.1246,75.8364',
        contactInfo: {
            phone: '+91-494-240-7356',
            email: 'mail@uoc.ac.in',
            website: 'https://www.uoc.ac.in',
            address: 'Thenhipalam, Malappuram 673635'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 7,000 - Rs. 16,000 per year',
        mediumOfInstruction: ['English', 'Malayalam'],
        establishedYear: 1968,
        affiliation: 'State University',
        placementRate: 63
    },
    {
        id: 'kalasalingam-university',
        name: 'Kalasalingam Academy of Research and Education',
        district: 'Virudhunagar',
        state: 'Tamil Nadu',
        type: 'Private',
        courses: ['B.Tech CSE', 'B.Tech ECE', 'B.Tech Mechanical', 'B.Sc Agriculture', 'B.Arch', 'MBA', 'B.Com'],
        eligibility: '10+2 with PCM/PCB. Admission via KUEE or JEE Main.',
        imageUrl: 'https://picsum.photos/seed/kalasalingam/600/400',
        about: 'A deemed university accredited with "A++" Grade by NAAC, offering a wide range of programs in engineering, science, and arts.',
        level: 'after_12th',
        fee: 'Rs. 1,00,000 - Rs. 2,00,000 per year',
        scholarships: 'Merit-based scholarships and sports quotas available.',
        latitude: 9.5667,
        longitude: 77.6833,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=9.5667,77.6833',
        contactInfo: {
            phone: '+91-4563-289042',
            email: 'info@kalasalingam.ac.in',
            website: 'https://kalasalingam.ac.in',
            address: 'Anand Nagar, Krishnankoil, Virudhunagar, Tamil Nadu 626126'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 60,000 - Rs. 80,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1984,
        affiliation: 'Deemed-to-be University',
        nirfRank: 50,
        placementRate: 90,
        averagePackage: '4.5 LPA'
    },
    {
        id: 'vardhaman-college',
        name: 'Vardhaman College of Engineering',
        district: 'Hyderabad',
        state: 'Telangana',
        type: 'Private',
        courses: ['B.Tech CSE', 'B.Tech AI & ML', 'B.Tech ECE', 'B.Tech Mechanical', 'MBA', 'M.Tech'],
        eligibility: '10+2 with PCM. Admission via TS EAMCET.',
        imageUrl: 'https://picsum.photos/seed/vardhaman/600/400',
        about: 'An autonomous institution affiliated with JNTUH, accredited with "A++" Grade by NAAC, known for its strong academic discipline.',
        level: 'after_12th',
        fee: 'Rs. 1,40,000 per year',
        scholarships: 'Government fee reimbursement for eligible students.',
        latitude: 17.2564,
        longitude: 78.3033,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=17.2564,78.3033',
        contactInfo: {
            phone: '+91-8688901557',
            email: 'info@vardhaman.org',
            website: 'https://vardhaman.org',
            address: 'Kacharam, Shamshabad, Hyderabad, Telangana 501218'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 75,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1999,
        affiliation: 'JNTUH',
        placementRate: 85,
        averagePackage: '6.14 LPA'
    },
    // ==================== POLYTECHNIC / DIPLOMA COLLEGES ====================
    {
        id: 'govt-poly-mumbai',
        name: 'Government Polytechnic, Mumbai',
        district: 'Mumbai',
        state: 'Maharashtra',
        type: 'Government',
        courses: ['Diploma in Computer Engineering', 'Diploma in Civil Engineering', 'Diploma in Mechanical Engineering', 'Diploma in Electrical Engineering', 'Diploma in Electronics'],
        eligibility: '10th Pass with Science & Maths. Admission via CAP rounds.',
        imageUrl: 'https://picsum.photos/seed/gpmumbai/600/400',
        about: 'One of the oldest and most prestigious polytechnic institutes in Maharashtra, offering autonomous diploma programs.',
        level: 'after_10th',
        fee: 'Rs. 6,000 - Rs. 10,000 per year',
        scholarships: 'MahaDBT scholarships for reserved categories and EBC.',
        latitude: 19.0607,
        longitude: 72.8362,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=19.0607,72.8362',
        contactInfo: {
            phone: '+91-22-2647-4780',
            email: 'principal@gpmumbai.ac.in',
            website: 'https://gpmumbai.ac.in',
            address: '49, Kherwadi, Ali Yawar Jung Marg, Bandra (East), Mumbai 400051'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 5,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1960,
        affiliation: 'MSBTE (Autonomous)',
        placementRate: 80
    },
    {
        id: 'acharya-poly-bangalore',
        name: 'Acharya Polytechnic, Bangalore',
        district: 'Bengaluru',
        state: 'Karnataka',
        type: 'Private',
        courses: ['Diploma in Computer Science', 'Diploma in Aeronautical Engineering', 'Diploma in Mechatronics', 'Diploma in Apparel Design'],
        eligibility: '10th Pass. Direct admission based on merit.',
        imageUrl: 'https://picsum.photos/seed/acharyapoly/600/400',
        about: 'Part of the massive Acharya Institutes campus, known for its excellent infrastructure and industry-oriented diploma courses.',
        level: 'after_10th',
        fee: 'Rs. 30,000 - Rs. 50,000 per year',
        scholarships: 'Merit scholarships by Acharya Institutes.',
        latitude: 13.0852,
        longitude: 77.4846,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=13.0852,77.4846',
        contactInfo: {
            phone: '+91-80-2372-2222',
            email: 'admissions@acharya.ac.in',
            website: 'https://www.acharya.ac.in',
            address: 'Acharya Dr. Sarvepalli Radhakrishnan Road, Soladevanahalli, Bangalore 560107'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 1,00,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1990,
        affiliation: 'DTE Karnataka',
        placementRate: 85
    },
    {
        id: 'pusa-poly-delhi',
        name: 'Pusa Institute of Technology, New Delhi',
        district: 'New Delhi',
        state: 'Delhi',
        type: 'Government',
        courses: ['Diploma in Automobile Engineering', 'Diploma in Civil Engineering', 'Diploma in Printing Technology', 'Diploma in Electronics'],
        eligibility: '10th Pass. Admission via Delhi CET.',
        imageUrl: 'https://picsum.photos/seed/pusapoly/600/400',
        about: 'A premier technical institute in Delhi, highly reputed for its engineering diploma courses and placement records.',
        level: 'after_10th',
        fee: 'Rs. 8,000 - Rs. 12,000 per year',
        scholarships: 'Delhi Government scholarships for meritorious students.',
        latitude: 28.6349,
        longitude: 77.1663,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.6349,77.1663',
        contactInfo: {
            phone: '+91-11-2584-7238',
            email: 'pit.delhi@nic.in',
            website: 'http://pit.delhi.gov.in',
            address: 'Pusa, New Delhi 110012'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 6,000 per year',
        mediumOfInstruction: ['English', 'Hindi'],
        establishedYear: 1962,
        affiliation: 'BTE Delhi',
        placementRate: 88
    },
    {
        id: 'govt-poly-pune',
        name: 'Government Polytechnic, Pune',
        district: 'Pune',
        state: 'Maharashtra',
        type: 'Government',
        courses: ['Diploma in Computer Engineering', 'Diploma in IT', 'Diploma in E&TC', 'Diploma in Dress Designing'],
        eligibility: '10th Pass. Admission via Centralized Admission Process (CAP).',
        imageUrl: 'https://picsum.photos/seed/gppune/600/400',
        about: 'An autonomous institute of Government of Maharashtra, known for academic excellence and strong alumni network.',
        level: 'after_10th',
        fee: 'Rs. 7,500 per year',
        scholarships: 'Various state government scholarships.',
        latitude: 18.5324,
        longitude: 73.8335,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=18.5324,73.8335',
        contactInfo: {
            phone: '+91-20-2567-6818',
            email: 'principal.gppune@dtemaharashtra.gov.in',
            website: 'http://www.gppune.ac.in',
            address: 'University Road, Ganeshkhind, Pune 411016'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 4,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1957,
        affiliation: 'MSBTE (Autonomous)',
        placementRate: 92
    },
    {
        id: 'thiagarajar-poly-salem',
        name: 'Thiagarajar Polytechnic College, Salem',
        district: 'Salem',
        state: 'Tamil Nadu',
        type: 'Government-Aided',
        courses: ['Diploma in Textile Technology', 'Diploma in Civil Engineering', 'Diploma in Mechanical Engineering', 'Diploma in Production Engineering'],
        eligibility: '10th Pass. Admission based on merit.',
        imageUrl: 'https://picsum.photos/seed/tptsalem/600/400',
        about: 'A highly awarded polytechnic college, famous for its textile technology and mechanical engineering programs.',
        level: 'after_10th',
        fee: 'Rs. 15,000 - Rs. 25,000 per year',
        scholarships: 'State government and management scholarships.',
        latitude: 11.6643,
        longitude: 78.1460,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=11.6643,78.1460',
        contactInfo: {
            phone: '+91-427-409-9100',
            email: 'principal@tpt.edu.in',
            website: 'https://www.tpt.edu.in',
            address: 'Junction Main Road, Salem, Tamil Nadu 636005'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 30,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1958,
        affiliation: 'DOTE Tamil Nadu',
        placementRate: 95
    },

    // ==================== ITI INSTITUTES ====================
    {
        id: 'govt-iti-guindy',
        name: 'Government Industrial Training Institute (ITI), Guindy',
        district: 'Chennai',
        state: 'Tamil Nadu',
        type: 'Government',
        courses: ['Electrician', 'Fitter', 'Welder', 'Turner', 'Machinist', 'Motor Mechanic Vehicle'],
        eligibility: '8th/10th Pass. Admission based on district merit list.',
        imageUrl: 'https://picsum.photos/seed/itiguindy/600/400',
        about: 'One of the premier ITIs in Tamil Nadu, offering a wide range of engineering and non-engineering trades.',
        level: 'after_10th',
        fee: 'Rs. 2,000 - Rs. 4,000 per year',
        scholarships: 'Stipend for trainees and scholarships for SC/ST.',
        latitude: 13.0102,
        longitude: 80.2157,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=13.0102,80.2157',
        contactInfo: {
            phone: '+91-44-2250-1002',
            email: 'guindyiti@gmail.com',
            website: 'https://skilltraining.tn.gov.in',
            address: 'Guindy, Chennai, Tamil Nadu 600032'
        },
        hostelAvailable: true,
        hostelFees: 'Minimal charges',
        mediumOfInstruction: ['Tamil', 'English'],
        establishedYear: 1960,
        affiliation: 'NCVT',
        placementRate: 80
    },
    {
        id: 'govt-iti-mumbai',
        name: 'Government Industrial Training Institute, Mumbai',
        district: 'Mumbai',
        state: 'Maharashtra',
        type: 'Government',
        courses: ['Electrician', 'Fitter', 'Draughtsman Civil', 'Information Technology', 'Refrigeration & AC'],
        eligibility: '10th Pass. Centralized admission process.',
        imageUrl: 'https://picsum.photos/seed/itimumbai/600/400',
        about: 'Located in the heart of Mumbai, providing skilled workforce to the industrial capital of India.',
        level: 'after_10th',
        fee: 'Rs. 3,000 - Rs. 5,000 per year',
        scholarships: 'Government stipend available.',
        latitude: 18.9828,
        longitude: 72.8347,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=18.9828,72.8347',
        contactInfo: {
            phone: '+91-22-2309-6918',
            email: 'iti.mumbai@dvet.gov.in',
            website: 'https://www.dvet.gov.in',
            address: '374, Sane Guruji Marg, Agripada, Mumbai 400011'
        },
        hostelAvailable: false,
        hostelFees: 'N/A',
        mediumOfInstruction: ['Marathi', 'English'],
        establishedYear: 1962,
        affiliation: 'NCVT',
        placementRate: 75
    },
    {
        id: 'govt-iti-pusa',
        name: 'Government ITI, Pusa',
        district: 'New Delhi',
        state: 'Delhi',
        type: 'Government',
        courses: ['Electrician', 'Fitter', 'Electronics Mechanic', 'Surveyor', 'Plumber'],
        eligibility: '10th Pass. Admission via Delhi ITI Online Admission.',
        imageUrl: 'https://picsum.photos/seed/itipusa/600/400',
        about: 'A leading ITI in North India with modern workshops and strong industry tie-ups.',
        level: 'after_10th',
        fee: 'Rs. 2,500 per year',
        scholarships: 'Fee concession and scholarships for Delhi residents.',
        latitude: 28.6349,
        longitude: 77.1663,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.6349,77.1663',
        contactInfo: {
            phone: '+91-11-2584-1234',
            email: 'itipusa@nic.in',
            website: 'https://itidelhi.admissions.nic.in',
            address: 'Pusa Campus, New Delhi 110012'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 3,000 per year',
        mediumOfInstruction: ['Hindi', 'English'],
        establishedYear: 1965,
        affiliation: 'NCVT',
        placementRate: 85
    },
    {
        id: 'govt-iti-bangalore',
        name: 'Government ITI (Dairy Circle), Bangalore',
        district: 'Bengaluru',
        state: 'Karnataka',
        type: 'Government',
        courses: ['Electrician', 'Fitter', 'Turner', 'Machinist', 'Welder'],
        eligibility: '10th Pass. Merit-based admission.',
        imageUrl: 'https://picsum.photos/seed/itibangalore/600/400',
        about: 'The most prominent ITI in Bangalore, known for its rigorous training and placement in tech and manufacturing sectors.',
        level: 'after_10th',
        fee: 'Rs. 2,000 - Rs. 4,000 per year',
        scholarships: 'Vidyasiri and other state scholarships.',
        latitude: 12.9352,
        longitude: 77.6060,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=12.9352,77.6060',
        contactInfo: {
            phone: '+91-80-2295-5555',
            email: 'principal.itidairy@karnataka.gov.in',
            website: 'https://emp.kar.nic.in',
            address: 'Dairy Circle, Hosur Road, Bangalore 560029'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 2,500 per year',
        mediumOfInstruction: ['Kannada', 'English'],
        establishedYear: 1955,
        affiliation: 'NCVT',
        placementRate: 88
    },
    {
        id: 'govt-iti-hyderabad',
        name: 'Government ITI, Mallepally',
        district: 'Hyderabad',
        state: 'Telangana',
        type: 'Government',
        courses: ['Electrician', 'Fitter', 'Diesel Mechanic', 'R&AC', 'Draughtsman Civil'],
        eligibility: '10th Pass. Admission via TS ITI Online.',
        imageUrl: 'https://picsum.photos/seed/itihyderabad/600/400',
        about: 'Oldest and largest ITI in Telangana, offering quality vocational training.',
        level: 'after_10th',
        fee: 'Rs. 3,000 per year',
        scholarships: 'State government scholarships available.',
        latitude: 17.3904,
        longitude: 78.4632,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=17.3904,78.4632',
        contactInfo: {
            phone: '+91-40-2334-5678',
            email: 'iti.mallepally@telangana.gov.in',
            website: 'https://iti.telangana.gov.in',
            address: 'Mallepally, Hyderabad 500057'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 3,000 per year',
        mediumOfInstruction: ['Telugu', 'English'],
        establishedYear: 1960,
        affiliation: 'NCVT',
        placementRate: 78
    },

    // ==================== ARTS & HUMANITIES COLLEGES ====================
    {
        id: 'st-xaviers-mumbai',
        name: 'St. Xavier\'s College, Mumbai',
        district: 'Mumbai',
        state: 'Maharashtra',
        type: 'Private (Autonomous)',
        courses: ['B.A. Psychology', 'B.A. Economics', 'B.A. Sociology', 'B.A. English Literature', 'BMM (Mass Media)'],
        eligibility: '10+2. Admission based on 12th marks and entrance for some courses.',
        imageUrl: 'https://picsum.photos/seed/stxaviers/600/400',
        about: 'A heritage institution known for its gothic architecture and vibrant cultural fest "Malhar". Top choice for Arts.',
        level: 'after_12th',
        fee: 'Rs. 7,000 - Rs. 30,000 per year',
        scholarships: 'Various trust and government scholarships.',
        latitude: 18.9426,
        longitude: 72.8319,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=18.9426,72.8319',
        contactInfo: {
            phone: '+91-22-2262-0661',
            email: 'webadmin@xaviers.edu',
            website: 'https://xaviers.edu',
            address: '5, Mahapalika Marg, Mumbai 400001'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 40,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1869,
        affiliation: 'University of Mumbai',
        nirfRank: 85,
        placementRate: 70,
        averagePackage: '5 LPA'
    },
    {
        id: 'loyola-chennai',
        name: 'Loyola College, Chennai',
        district: 'Chennai',
        state: 'Tamil Nadu',
        type: 'Private (Autonomous)',
        courses: ['B.A. Economics', 'B.A. English', 'B.A. History', 'B.A. Sociology', 'B.Sc. Visual Communication'],
        eligibility: '10+2. Admission based on merit and interview.',
        imageUrl: 'https://picsum.photos/seed/loyola/600/400',
        about: 'Consistently ranked among the top 5 colleges in India. Known for academic discipline and social service.',
        level: 'after_12th',
        fee: 'Rs. 12,000 - Rs. 50,000 per year',
        scholarships: 'Management scholarships for poor and deserving students.',
        latitude: 13.0624,
        longitude: 80.2334,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=13.0624,80.2334',
        contactInfo: {
            phone: '+91-44-2817-8200',
            email: 'helpdesk@loyolacollege.edu',
            website: 'https://www.loyolacollege.edu',
            address: 'Sterling Road, Nungambakkam, Chennai 600034'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 35,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1925,
        affiliation: 'University of Madras',
        nirfRank: 7,
        placementRate: 80,
        averagePackage: '5.5 LPA'
    },
    {
        id: 'fergusson-pune',
        name: 'Fergusson College, Pune',
        district: 'Pune',
        state: 'Maharashtra',
        type: 'Private (Autonomous)',
        courses: ['B.A. Psychology', 'B.A. Economics', 'B.A. Political Science', 'B.A. English'],
        eligibility: '10+2. Admission based on merit.',
        imageUrl: 'https://picsum.photos/seed/fergusson/600/400',
        about: 'A historical college founded by freedom fighters. Famous for its humanities and science programs.',
        level: 'after_12th',
        fee: 'Rs. 9,000 - Rs. 25,000 per year',
        scholarships: 'State and central government scholarships.',
        latitude: 18.5236,
        longitude: 73.8410,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=18.5236,73.8410',
        contactInfo: {
            phone: '+91-20-6765-6000',
            email: 'principal@fergusson.edu',
            website: 'https://www.fergusson.edu',
            address: 'FC Road, Pune 411004'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 30,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1885,
        affiliation: 'Savitribai Phule Pune University',
        nirfRank: 90,
        placementRate: 60,
        averagePackage: '4 LPA'
    },
    {
        id: 'presidency-kolkata',
        name: 'Presidency University, Kolkata',
        district: 'Kolkata',
        state: 'West Bengal',
        type: 'Government',
        courses: ['B.A. Bengali', 'B.A. English', 'B.A. History', 'B.A. Philosophy', 'B.A. Political Science'],
        eligibility: '10+2. Admission via PUBDET entrance exam.',
        imageUrl: 'https://picsum.photos/seed/presidency/600/400',
        about: 'One of the oldest and most prestigious institutions in India, offering high-quality education in liberal arts.',
        level: 'after_12th',
        fee: 'Rs. 4,000 - Rs. 6,000 per year',
        scholarships: 'Swami Vivekananda Merit-cum-Means Scholarship.',
        latitude: 22.5753,
        longitude: 88.3639,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=22.5753,88.3639',
        contactInfo: {
            phone: '+91-33-2241-1960',
            email: 'registrar@presiuniv.ac.in',
            website: 'https://www.presiuniv.ac.in',
            address: '86/1, College Street, Kolkata 700073'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 5,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1817,
        affiliation: 'State University',
        nirfRank: 45,
        placementRate: 50,
        averagePackage: '4.5 LPA'
    },
    {
        id: 'mcc-chennai',
        name: 'Madras Christian College (MCC), Chennai',
        district: 'Chennai',
        state: 'Tamil Nadu',
        type: 'Private (Autonomous)',
        courses: ['B.A. Journalism', 'B.A. English', 'B.A. Economics', 'B.A. History', 'BSW (Social Work)'],
        eligibility: '10+2. Admission based on merit.',
        imageUrl: 'https://picsum.photos/seed/mcc/600/400',
        about: 'Known for its lush green campus and holistic education. Excellent for liberal arts and sciences.',
        level: 'after_12th',
        fee: 'Rs. 20,000 - Rs. 40,000 per year',
        scholarships: 'College and government scholarships.',
        latitude: 12.9226,
        longitude: 80.1274,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=12.9226,80.1274',
        contactInfo: {
            phone: '+91-44-2239-0675',
            email: 'principal@mcc.edu.in',
            website: 'https://mcc.edu.in',
            address: 'Tambaram, Chennai 600059'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 35,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1837,
        affiliation: 'University of Madras',
        nirfRank: 16,
        placementRate: 75,
        averagePackage: '4.5 LPA'
    },

    // ==================== COMMERCE & MANAGEMENT COLLEGES ====================
    {
        id: 'nm-college-mumbai',
        name: 'Narsee Monjee College of Commerce and Economics, Mumbai',
        district: 'Mumbai',
        state: 'Maharashtra',
        type: 'Private (Autonomous)',
        courses: ['B.Com', 'BMS', 'B.Com (Accounting & Finance)', 'B.Com (Financial Markets)'],
        eligibility: '10+2. Admission based on merit (very high cutoffs).',
        imageUrl: 'https://picsum.photos/seed/nmcollege/600/400',
        about: 'A premier commerce college in Mumbai, known for its rigorous academic standards and CA-friendly environment.',
        level: 'after_12th',
        fee: 'Rs. 35,000 - Rs. 50,000 per year',
        scholarships: 'Government scholarships available.',
        latitude: 19.1035,
        longitude: 72.8377,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=19.1035,72.8377',
        contactInfo: {
            phone: '+91-22-4233-8000',
            email: 'info@nmcce.ac.in',
            website: 'https://nmcce.ac.in',
            address: 'Vile Parle (West), Mumbai 400056'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 80,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1964,
        affiliation: 'University of Mumbai',
        placementRate: 90,
        averagePackage: '6 LPA'
    },
    {
        id: 'sjcc-bangalore',
        name: 'St. Joseph\'s College of Commerce, Bangalore',
        district: 'Bengaluru',
        state: 'Karnataka',
        type: 'Private (Autonomous)',
        courses: ['B.Com', 'BBA', 'B.Com (International Accounting)', 'BBA (Entrepreneurship)'],
        eligibility: '10+2. Admission via Entrance Exam and Interview.',
        imageUrl: 'https://picsum.photos/seed/sjcc/600/400',
        about: 'One of the best commerce colleges in South India, focusing on holistic development and professional skills.',
        level: 'after_12th',
        fee: 'Rs. 80,000 - Rs. 1,50,000 per year',
        scholarships: 'Management scholarships for needy students.',
        latitude: 12.9719,
        longitude: 77.6070,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=12.9719,77.6070',
        contactInfo: {
            phone: '+91-80-2536-0644',
            email: 'info@sjcc.edu.in',
            website: 'https://www.sjcc.edu.in',
            address: '163, Brigade Road, Bangalore 560025'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 50,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1972,
        affiliation: 'Bengaluru City University',
        nirfRank: 65,
        placementRate: 92,
        averagePackage: '6.5 LPA'
    },
    {
        id: 'goenka-kolkata',
        name: 'Goenka College of Commerce and Business Administration, Kolkata',
        district: 'Kolkata',
        state: 'West Bengal',
        type: 'Government',
        courses: ['B.Com (Hons)', 'M.Com', 'MBA'],
        eligibility: '10+2. Admission based on merit.',
        imageUrl: 'https://picsum.photos/seed/goenka/600/400',
        about: 'A heritage government college in Kolkata, exclusively for commerce education. Very affordable and high quality.',
        level: 'after_12th',
        fee: 'Rs. 2,000 - Rs. 4,000 per year',
        scholarships: 'Kanyashree and other state scholarships.',
        latitude: 22.5689,
        longitude: 88.3646,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=22.5689,88.3646',
        contactInfo: {
            phone: '+91-33-2241-2216',
            email: 'principal@goenkacollege.net',
            website: 'http://goenkacollege.net',
            address: '210, B.B. Ganguly Street, Kolkata 700012'
        },
        hostelAvailable: false,
        hostelFees: 'N/A',
        mediumOfInstruction: ['English'],
        establishedYear: 1905,
        affiliation: 'University of Calcutta',
        placementRate: 85,
        averagePackage: '5 LPA'
    },
    {
        id: 'christ-univ-bangalore',
        name: 'Christ University, Bangalore',
        district: 'Bengaluru',
        state: 'Karnataka',
        type: 'Private (Deemed)',
        courses: ['BBA', 'B.Com (Hons)', 'B.Com (Finance & Accountancy)', 'BBA (FinTech)'],
        eligibility: '10+2. Admission via CUET (Christ University Entrance Test).',
        imageUrl: 'https://picsum.photos/seed/christ/600/400',
        about: 'A top-ranked deemed university known for its strict discipline, vibrant campus culture, and excellent management programs.',
        level: 'after_12th',
        fee: 'Rs. 1,50,000 - Rs. 2,50,000 per year',
        scholarships: 'Merit and financial aid scholarships.',
        latitude: 12.9344,
        longitude: 77.6060,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=12.9344,77.6060',
        contactInfo: {
            phone: '+91-80-4012-9100',
            email: 'mail@christuniversity.in',
            website: 'https://christuniversity.in',
            address: 'Hosur Road, Bangalore 560029'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 40,000 - Rs. 80,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1969,
        affiliation: 'Deemed University',
        nirfRank: 60,
        placementRate: 95,
        averagePackage: '7 LPA'
    },
    {
        id: 'hindu-college-delhi',
        name: 'Hindu College, New Delhi',
        district: 'New Delhi',
        state: 'Delhi',
        type: 'Government',
        courses: ['B.Com (Hons)', 'B.A. Economics (Hons)', 'B.Sc. Statistics'],
        eligibility: '10+2. Admission via CUET-UG.',
        imageUrl: 'https://picsum.photos/seed/hindu/600/400',
        about: 'One of the most prestigious colleges under Delhi University, known for its vibrant political and cultural life.',
        level: 'after_12th',
        fee: 'Rs. 18,000 - Rs. 22,000 per year',
        scholarships: 'Various government and college scholarships.',
        latitude: 28.6844,
        longitude: 77.2104,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.6844,77.2104',
        contactInfo: {
            phone: '+91-11-2766-7184',
            email: 'principal@hinducollege.org',
            website: 'https://hinducollege.ac.in',
            address: 'University Enclave, Delhi 110007'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 30,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1899,
        affiliation: 'University of Delhi',
        nirfRank: 2,
        placementRate: 90,
        averagePackage: '10 LPA'
    },

    // ==================== MEDICAL & NURSING COLLEGES ====================
    {
        id: 'cmc-vellore',
        name: 'Christian Medical College (CMC), Vellore',
        district: 'Vellore',
        state: 'Tamil Nadu',
        type: 'Private (Trust)',
        courses: ['MBBS', 'B.Sc Nursing', 'BPT', 'BOT', 'B.Sc MLT'],
        eligibility: '10+2 with PCB. Admission via NEET-UG.',
        imageUrl: 'https://picsum.photos/seed/cmcvellore/600/400',
        about: 'One of the best medical colleges in India, known for its service-oriented approach and world-class healthcare education.',
        level: 'after_12th',
        fee: 'Rs. 50,000 per year (Highly subsidized)',
        scholarships: 'Full scholarships for needy students.',
        latitude: 12.9246,
        longitude: 79.1348,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=12.9246,79.1348',
        contactInfo: {
            phone: '+91-416-228-1000',
            email: 'registrar@cmcvellore.ac.in',
            website: 'https://www.cmch-vellore.edu',
            address: 'Ida Scudder Road, Vellore, Tamil Nadu 632004'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 20,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1900,
        affiliation: 'MGR Medical University',
        nirfRank: 3,
        placementRate: 100,
        averagePackage: '12 LPA'
    },
    {
        id: 'kgmu-lucknow',
        name: 'King George\'s Medical University (KGMU), Lucknow',
        district: 'Lucknow',
        state: 'Uttar Pradesh',
        type: 'Government',
        courses: ['MBBS', 'BDS', 'B.Sc Nursing'],
        eligibility: '10+2 with PCB. Admission via NEET-UG.',
        imageUrl: 'https://picsum.photos/seed/kgmu/600/400',
        about: 'A historic medical university in North India, offering excellent clinical exposure and research opportunities.',
        level: 'after_12th',
        fee: 'Rs. 55,000 per year',
        scholarships: 'UP State Government scholarships.',
        latitude: 26.8693,
        longitude: 80.9150,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=26.8693,80.9150',
        contactInfo: {
            phone: '+91-522-225-7540',
            email: 'registrar@kgmcindia.edu',
            website: 'https://www.kgmu.org',
            address: 'Shah Mina Road, Chowk, Lucknow 226003'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 6,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1911,
        affiliation: 'Medical University',
        nirfRank: 12,
        placementRate: 100,
        averagePackage: '10 LPA'
    },
    {
        id: 'grant-medical-mumbai',
        name: 'Grant Medical College & Sir J.J. Group of Hospitals, Mumbai',
        district: 'Mumbai',
        state: 'Maharashtra',
        type: 'Government',
        courses: ['MBBS', 'B.Sc Nursing', 'BPMT'],
        eligibility: '10+2 with PCB. Admission via NEET-UG.',
        imageUrl: 'https://picsum.photos/seed/grantmedical/600/400',
        about: 'One of the oldest medical colleges in Asia, attached to the massive J.J. Hospital, providing unmatched clinical experience.',
        level: 'after_12th',
        fee: 'Rs. 1,10,000 per year',
        scholarships: 'State government scholarships for reserved categories.',
        latitude: 18.9633,
        longitude: 72.8333,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=18.9633,72.8333',
        contactInfo: {
            phone: '+91-22-2373-5555',
            email: 'dean_gmcjjh@maha.gov.in',
            website: 'https://ggmcjjh.com',
            address: 'Byculla, Mumbai 400008'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 4,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1845,
        affiliation: 'MUHS Nashik',
        nirfRank: 15,
        placementRate: 100,
        averagePackage: '9 LPA'
    },
    {
        id: 'mmc-chennai',
        name: 'Madras Medical College (MMC), Chennai',
        district: 'Chennai',
        state: 'Tamil Nadu',
        type: 'Government',
        courses: ['MBBS', 'B.Pharm', 'B.Sc Nursing', 'BPT'],
        eligibility: '10+2 with PCB. Admission via NEET-UG.',
        imageUrl: 'https://picsum.photos/seed/mmc/600/400',
        about: 'The oldest medical college in India, attached to the Rajiv Gandhi Government General Hospital.',
        level: 'after_12th',
        fee: 'Rs. 13,600 per year',
        scholarships: 'TN State Government scholarships.',
        latitude: 13.0827,
        longitude: 80.2707,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=13.0827,80.2707',
        contactInfo: {
            phone: '+91-44-2530-5000',
            email: 'deanmmc@tn.gov.in',
            website: 'http://www.mmc.ac.in',
            address: 'E.V.R Periyar Salai, Park Town, Chennai 600003'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 5,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1835,
        affiliation: 'MGR Medical University',
        nirfRank: 11,
        placementRate: 100,
        averagePackage: '10 LPA'
    },
    {
        id: 'st-johns-bangalore',
        name: 'St. John\'s Medical College, Bangalore',
        district: 'Bengaluru',
        state: 'Karnataka',
        type: 'Private (Trust)',
        courses: ['MBBS', 'B.Sc Nursing', 'BPT', 'B.Sc MLT'],
        eligibility: '10+2 with PCB. Admission via NEET-UG.',
        imageUrl: 'https://picsum.photos/seed/stjohns/600/400',
        about: 'A premier medical institution known for its values, research, and community health services.',
        level: 'after_12th',
        fee: 'Rs. 6,00,000 per year',
        scholarships: 'Scholarships available for meritorious and needy students.',
        latitude: 12.9303,
        longitude: 77.6206,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=12.9303,77.6206',
        contactInfo: {
            phone: '+91-80-2206-5000',
            email: 'dean.sjmc@stjohns.in',
            website: 'https://www.stjohns.in',
            address: 'Sarjapur Road, Bangalore 560034'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 60,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1963,
        affiliation: 'RGUHS',
        nirfRank: 19,
        placementRate: 100,
        averagePackage: '11 LPA'
    }
];

/**
 * TEMPLATE FOR ADDING NEW COLLEGES:
 * 
 * {
 *     id: 'unique-id-kebab-case', // e.g., 'delhi-univ'
 *     name: 'Official College Name',
 *     district: 'District Name',
 *     state: 'State Name',
 *     type: 'Government' | 'Private' | 'Public-Private',
 *     courses: ['Course 1', 'Course 2', ...], // Array of course names
 *     eligibility: 'Eligibility criteria with admission process',
 *     imageUrl: 'https://picsum.photos/seed/uniqueseed/600/400', // Or real image URL
 *     about: 'Brief description of the college in 1-2 sentences',
 *     level: 'after_10th' | 'after_12th',
 *     fee: 'Rs. X,XXX - Rs. X,XXX per year',
 *     scholarships: 'Description of available scholarships',
 *     latitude: 00.0000, // Get from Google Maps
 *     longitude: 00.0000, // Get from Google Maps
 *     contactInfo: {
 *         phone: '+91-XXX-XXX-XXXX',
 *         email: 'email@college.ac.in',
 *         website: 'https://www.college.ac.in',
 *         address: 'Full postal address'
 *     },
 *     hostelAvailable: true | false,
 *     hostelFees: 'Rs. X,XXX - Rs. X,XXX per year', // Optional
 *     mediumOfInstruction: ['English', 'Hindi', ...], // Array of languages
 *     establishedYear: YYYY, // Optional
 *     affiliation: 'University/Board name', // Optional
 *     nirfRank: XX, // Optional, only if ranked
 *     placementRate: 0-100, // Optional, percentage
 *     averagePackage: 'X LPA' // Optional
 * },
 */
